name: "Test & Deploy"
on: [push, pull_request]
env:
  DIRENV_WARN_TIMEOUT: 5m
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v12
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - name: Check Nix flake Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
      - run: nix flake check --no-build
      - name: Install direnv with Nix
        uses: aldoborrero/direnv-nix-action@v2
        with:
          use_nix_profile: true
      - name: Pre-commit checks
        run: pre-commit run --all-files
      - name: Test
        run: npm run test:coverage
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage/
  npm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v12
      - uses: DeterminateSystems/magic-nix-cache-action@v7
      - name: Get tag version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_tag_version
        run: echo TAG_VERSION=${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT
      - name: Set package version
        if: startsWith(github.ref, 'refs/tags/')
        run: npm version ${{steps.get_tag_version.outputs.TAG_VERSION}}
      - name: Build
        run: npm run build
      - name: Archive generated npm package
        uses: actions/upload-artifact@v4
        with:
          name: npm-package
          path: planet-a-avsc-zstandard-codec-*.tgz
      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: nix develop --ignore-environment --keep NODE_AUTH_TOKEN --command bash -c 'pushd npm ; npm publish ; popd'
